CAPTURE:
  SAVE_WIDTH: 3264
  SAVE_HEIGHT: 2464
  CAM_WIDTH: 816
  CAM_HEIGHT: 612
  CAM_NO: 0
  CAM_ROTATE: 0
  CAM_NAME: "cam"
  OUTPUT_PATH: "./outputs"
CONTROL:
  CAPTURE: "c"
  CLOSE: "esc"
LOGGER:
  NAME: "cam-capture-logger-1"
  CONF_PATH: "./cam_capture_client/config/logger.json"